name: Huxle

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --frozen-lockfile
      - name: Run linting
        run: yarn lint
  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --frozen-lockfile
      - name: Run typechecking
        run: yarn type-check

  Build-Image:
    runs-on: ubuntu-latest
    needs: [Lint, Typecheck]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: angry-bot
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and upload Docker image
        run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/huxle:${{ steps.package-version.outputs.current-version }} -t ${{ secrets.DOCKER_USERNAME }}/huxle:latest -f ./Dockerfile --platform=linux/arm64,linux/amd64,linux/arm/v7,linux/arm/v6 -o type=registry .
